### ISSUE TITLE
PitSprint (and others?) have loot in vaults replaced by large amounts of dungeon exits.

### ISSUE THREAD

**Issue by SevenDeadlySins** [crawl/crawl#486] opened 2017-03-05 11:48 UTC
Bug occurred when playing Sprint a few days ago on CBRO Webtiles.

http://crawl.berotato.org/crawl/morgue/SevenDeadlySins/morgue-SevenDeadlySins-20170227-122118.txt

Version 0.20-a0-787-g4ba4951 (webtiles)

Not visible in the map there, but in a few different loot areas of the inner vaults, large swaths of loot were replaced by dungeon exits. Probably related to a change to glyph definitions in vault files, which were not updated in Sprints.

**Comment by MarvinPA** [comment] 2017-03-05 11:54
The Mantis issue for this is here: https://crawl.develz.org/mantis/view.php?id=10954 (closing this as duplicate).

I'm unable to reproduce it locally, so if anyone else can do so would be appreciated.

**Closed by MarvinPA** 2017-03-05 11:54 UTC
