### ISSUE TITLE
On upgrade, the des/db cache isn't automatically rebuilt

### ISSUE THREAD

**Issue by catern** [crawl/crawl#1702] opened 2021-01-27 16:01 UTC
**PLATFORM and OS or BROWSER:**
Local tiles, NixOS

**DCSS VERSION AND GAME INFORMATION:**
0.26

**DESCRIPTION:**
When upgrading DCSS version (e.g., 0.25 to 0.26), the ~/.crawl/des and ~/.crawl/db caches should be invalidated and rebuilt on the first run of the new version of crawl.

Instead, DCSS just uses the cache for the old version, which results in lots of oddities and bugs, as in https://github.com/crawl/crawl/issues/1225 AFAIK, most Linux distributions use a shared ~/.crawl directory for all versions (that's how DCSS is configured by default), so I think this issue should be somewhat widespread...

This can be worked around by deleting these caches manually, but every time I upgrade I forget. :)

Most simply, maybe ~/.crawl/db could just be tagged with a version or something, so that it can be automatically rebuilt - in the same way save files are tagged with a version and can't be loaded after upgrading.

**Comment by rawlins** [comment] 2021-01-27 16:26
I do still think this may be a packaging issue somehow, as suggested in #1225. Crawl has code to detect outdated des caches, and on mac which also uses a shared save directory, the des cache is reliably invalidated and rebuilt when switching versions (I think also on other linux systems, though I can't swear to this). I'm not sure offhand what cues it is using to do this though or how it could be going wrong on nixos, I'll check at some point.

**Comment by catern** [comment] 2021-01-27 16:56
I just had a look at (some of?) the des invalidation code (I think it's the verify_file_version function?). It looks like it uses an explicit version tag embedded into the cache files. I'm not sure why that's not working.

It looks like it *also* uses the mtime of the crawl data files, though - that's embedded in the cache files as well as a secondary version. In NixOS all package files have an mtime of 0 (for reproducibility reasons) so the mtime won't be different between different crawl versions, so the mtime won't help.

That should be fine though if the explicit version tag is working. Not sure why it isn't?

**Comment by catern** [comment] 2021-01-27 17:09
Oh I guess the explicit version tag is just a file format thing. TAG_MAJOR_VERSION hasn't been changed since 2012. TAG_MINOR_VERSION seems to change regularly, but the file version check is:
```
        return major == TAG_MAJOR_VERSION
               && minor <= TAG_MINOR_VERSION
               && word == WORD_LEN
               && t == mtime;
```
So since the minor version embedded in the old cache is less than the new TAG_MINOR_VERSION, the cache isn't invalidated.

So I guess only the mtime matters to cause the cache invalidation. Which works fine for MacOS and all other platforms, but not when mtime is 0.

Maybe the check for TAG_MINOR_VERSION should be == instead of <=? It seems like TAG_MINOR_VERSION changes at least once between every release, so that would get the desirable invalidation. (although I guess it's not technically tied to the release and the actual content of the data files)

Maybe some kind of special case for mtime == 0?

A more robust change, I guess, would be to actually embed the DCSS version in the files. But that would require changing the format...

Oh, here's an idea: Add the DCSS version to the mtime when embedding it or doing the comparison. The combination will monotonically increase when either the files or changed or the version increases. That seems pretty robust

**Comment by rawlins** [comment] 2021-02-09 14:58
Thanks for looking into this! So if I'm understanding this correctly NixOS sets mtime to 0 for all package files, for reproducible build/packaging purposes, but we rely on mtime to detect cache versioning. I have four suggestions:

* simplest, probably: use `#define DGL_VERSIONED_CACHE_DIR` for nixos builds. Description (see AppHdr.h):
    // Create .des and database cache files in a directory named with the
    // game version so that multiple save-compatible Crawl versions can
    // share the same savedir.

This `#define` is used on most public servers so is well tested, and probably will do what you want while keeping a shared save directory (test it out first though, not sure if any offline builds are using it in quite this way). It uses full version as determined by commit hash. To be clear, you don't want the entire set of `DGAMELAUNCH` `#define`s, which are intended for a very specific server environment.

* Use a versioned `SAVEDIR` in the build process (which will separate out more than just the cache by version); there's no built-in way of setting the version but this would allow more customizability for packaging purposes.

* re mtime, Do you know if there's any flexibility in this? `des` files aren't generated or modified as part of the build/packaging process, and I think what we're seeing here is in some sense a failure of reproducible builds (because it's not replicating differences between versions). When I look at what debian does (this is where I've interacted with reproducible builds before), it does not seem that they ended up taking such a hard line, see e.g. discussion about clamping mtime relative to build times towards the end of: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=759886.

*  It may be possible to use exact minor tag comparison when mtime is set to 0, but this seems extremely special-cased. Given that this is (as far as I know) a rather unique semantics for mtime,  possibly this would be something that shouldn't be merged into the main dcss repo, but rather applied as a patch by packagers who are using mtime this way.

The backward compatibility in the minor tag there is intentional; dcss is backwards compatible within the major tag version (which as you say hasn't changed in some time). What this code is trying to do is detect if the cache is built against a *later* version of crawl, because that may lead to binary incompatibilities even if the des file itself hasn't changed. But a version built against a previous minor tag, where the mtime hasn't changed since that version, shouldn't need to be rebuilt because it will be a compatible format.

**Closed** 2021-03-27 16:41 UTC

**Comment by rawlins** [comment] 2021-03-27 16:42
Just to follow up, I think versioned cache directories are the best solution to this situation, and the commit I just made should make it a bit clearer to anyone wanting to follow up how to accomplish this. (Short answer, after that commit, pass something like `EXTERNAL_DEFINES="-DVERSIONED_CACHE_DIR"` to the make call.)
