### ISSUE TITLE
Crash: Octopode Chaos Knight, "invalid cursor position"

### ISSUE THREAD

**Issue by joshhansen** [crawl/crawl#3045] opened 2023-03-10 01:40 UTC
**PLATFORM and OS or BROWSER:**
Console
Linux Mint 21.1 x86_64
Installed from the PPA

**DCSS VERSION AND GAME INFORMATION:**
```
crawl --version
Crawl version 0.29.1
Save file version 34.248
Compiled with GCC 8.3.0
Build platform: x86_64-linux-gnu
Platform: x86_64-linux-gnu
CFLAGS: -O2 -fdebug-prefix-map=/build/crawl-0.29.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -flto=jobserver -fwhole-program -fno-fat-lto-objects -pipe -Wall -Wformat-security -Wundef -Wextra -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-type-limits -Wno-uninitialized -Wno-array-bounds -Wmissing-declarations -Wredundant-decls -Wno-parentheses -Wwrite-strings -Wshadow -pedantic -Wuninitialized -Iutil -I. -isystem /usr/include/lua5.1 -DWIZARD -DASSERTS -DCLUA_BINDINGS -DSAVE_DIR_PATH="~/.crawl" -DDATA_DIR_PATH="/usr/share/crawl/" -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600
LDFLAGS: -rdynamic -fuse-ld=gold -O2 -fdebug-prefix-map=/build/crawl-0.29.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -flto=jobserver -fwhole-program -fno-fat-lto-objects 
```

**DESCRIPTION:**
I had just equipped a second short blade weapon, at least that's the last thing I remember doing.

The error output:
```
ASSERT(valid_cursor_pos(pos.x, pos.y, region)) in 'libconsole.h' at line 67 failed. (invalid cursor position 31,-2 in region 1)

We crashed! This is likely due to a bug in Crawl. 
Please submit a bug report at https://github.com/crawl/crawl/issues or at
https://crawl.develz.org/mantis/ and include:
- The crash report: /home/josh/.crawl/morgue/crash-Giennel-20230309-172014.txt
- Your save file: /home/josh/.crawl/saves/Giennel.cs
- A description of what you were doing when this crash occurred.

Aborted (core dumped)
```

**EXTRA FILES:**
See attached morgue, save, and coredump files.

[crawlcrash.zip](https://github.com/crawl/crawl/files/10937696/crawlcrash.zip)

**Comment by robertxgray** [comment] 2023-04-02 13:50
Possible duplicate of #1497. At least they crash in the same line of code. Is is possible that the terminal's size changed when it crashed?

**Closed** 2023-05-13 10:35 UTC
Labels: bug, console, crash
