### ISSUE TITLE
Ashenzari clarity does not prevent necklace of bloodlust's *rage

### ISSUE THREAD

**Issue by Jackiecrazy** [crawl/crawl#2105] opened 2021-09-01 03:09 UTC
**PLATFORM and OS or BROWSER:**local tiles 0.28-a0-313-gbc0475efdd

**DESCRIPTION:**
Necklace of Bloodlust seems to bypass clarity. After gaining Ashenzari piety to the point where I gained clarity, equipping the necklace will still randomly berserk me on melee hit. There is no indication that this should be the case in either description, so I assume that this is a bug.

**EXTRA FILES:**
[morgue](https://github.com/crawl/crawl/files/7087953/Sutoku.txt)
[save](https://github.com/crawl/crawl/files/7087954/Sutoku.zip)

**Comment by ebering** [comment] 2021-09-12 09:29
This was fixed in 51f8dfeb47

**Closed by ebering** 2021-09-12 09:29 UTC

**Comment by Jackiecrazy** [comment] 2021-09-12 16:55
35c06b56dfa878997582c328f24dd6b833a57f2a reverts the change. I assume that *rage bypasses clarity again now?

**Comment by ebering** [comment] 2021-09-12 17:15
Yes, per the commit message of the linked commit, this is intended behavior for *Rage items.
