### ISSUE TITLE
Crashes/coredumps from 0.32.0 when trying to cast starburst (maybe some other spells too) still happing in 0.32.1. Now crashes when trying to open list of spells to cast with z/Z

### ISSUE THREAD

**Issue by van9k** [crawl/crawl#4152] opened 2024-11-30 15:19 UTC
[crash-ttt-20241130-180925.txt](https://github.com/user-attachments/files/17965851/crash-ttt-20241130-180925.txt)
[crash-ttt-20241130-175521.txt](https://github.com/user-attachments/files/17965852/crash-ttt-20241130-175521.txt)
[crash-ttt-20241130-175433.txt](https://github.com/user-attachments/files/17965853/crash-ttt-20241130-175433.txt)
[crash-ttt-20241130-175205.txt](https://github.com/user-attachments/files/17965854/crash-ttt-20241130-175205.txt)
[crash-ttt-20241021-204857.txt](https://github.com/user-attachments/files/17965855/crash-ttt-20241021-204857.txt)
[crash-ttt-20241019-030857.txt](https://github.com/user-attachments/files/17965856/crash-ttt-20241019-030857.txt)
[crash-ttt-20241019-030829.txt](https://github.com/user-attachments/files/17965857/crash-ttt-20241019-030829.txt)
[crash-ttt-20241019-030637.txt](https://github.com/user-attachments/files/17965858/crash-ttt-20241019-030637.txt)
[crash-ttt-20241019-023254.txt](https://github.com/user-attachments/files/17965860/crash-ttt-20241019-023254.txt)

**PLATFORM and OS or BROWSER:**
"local tiles", "console". 6.6.54-2-MANJARO #1 SMP PREEMPT_DYNAMIC Tue Oct  8 03:11:08 UTC 2024 x86_64 GNU/Linux

**DCSS VERSION AND GAME INFORMATION:**
"0.32.0", "0.32.1".

**DESCRIPTION:**
Looks like high lvl spells like starburst (and now even opening spell list with z/Z) causing game to crash in 0.32.0-0.32.1 Maybe save inheriting problems from .0 and new game will not be crashing, didn't check it out.

**Comment by DracoOmega** [comment] 2024-12-01 02:59
Could you possibly attach a save file where this is happening?

**Comment by van9k** [comment] 2024-12-01 05:50
[ttt.cs.zip](https://github.com/user-attachments/files/17967957/ttt.cs.zip)
I found tts.cs in save directory, guess it is it. If i could help anyhow else, please ask!

**Comment by van9k** [comment] 2024-12-01 05:53
What i want to add, is that location of character seems not to matter, it was crashing, i imagine, while drawing geometry of spell (both in tiles and console version)

**Comment by d-strickland** [comment] 2024-12-01 21:04
I just had a crash that looks related in WebTiles, apparently during a monster spell cast.

https://crawl.akrasiac.org/rawdata/davinchilada/crash-davinchilada-20241201-205539.txt

**Comment by DracoOmega** [comment] 2024-12-01 23:54
I'm afraid (as I feared) that I cannot reproduce this crash locally, even using the provided save file, on either Linux or Windows. The crash does appear to be coming from attempting to do raycasting for Starburst, but the function that is asserting is code that is used extremely widely in the codebase and has not been changed in *at least* 9 years. Given how constantly rays are used in Crawl and the fact that this isn't a commonly reported bug makes me worry that this is somehow a very system-specific issue (and I'm not really sure where to go from there, I'm afraid)

**Comment by DracoOmega** [comment] 2024-12-01 23:55
> I just had a crash that looks related in WebTiles, apparently during a monster spell cast.
> 
> https://crawl.akrasiac.org/rawdata/davinchilada/crash-davinchilada-20241201-205539.txt

That bug is almost certainly unrelated. (It is a known, if somewhat rare, problem with Thunderhulk's Call Down Lightning attempting to bolt bounce despite having no path.)

**Comment by WizardIke** [comment] 2024-12-03 02:29
I was able to replicate this using the crawl-tiles package installed with pacman on manjaro. The bug was not the same each time I loaded the game and cast from the same spot and ranged from crashing when trying to cast to warning if I wanted to target myself and then crashing when cast to not shooting out beams in most directions. If it asked if I wanted to target myself and I said no and then cast again without moving it would very often ask if I wanted to target myself again.

**Comment by WizardIke** [comment] 2024-12-04 08:24
The crash seems to be caused by two separate bugs. During raycasting a ray only counts as passing through a tile if it passes the the central diamond formed by chopping the corners off the tile. When a ray travels from the center of a tile in a cardinal direction it will pass through the corner of one diamond and into another diamond which has special handling. however, if a ray travels in an almost cardinal direction, some parts of the code will treat it as passing through the corner between the diamonds and others won't leading to a crash.

However, starburst shouldn't shoot rays in almost cardinal directions which leads to the second bug. We use the following code to determine the offset from the caster to the end of each bolt shot out by starburst
```
vector<coord_def> offsets = { coord_def(range, 0),
                                coord_def(range, range),
                                coord_def(0, range),
                                coord_def(-range, range),
                                coord_def(-range, 0),
                                coord_def(-range, -range),
                                coord_def(0, -range),
                                coord_def(range, -range) };
```
however, on the buggy crawl-tiles package the elements in offsets were wrong and somewhat random and would look something like
```
{{x = -8192, y = 16777216},
{x = 1451957184, y = 21845},
{x = -17872, y = 32767} ,
{x = -564717644, y = 32767},
{x = 32, y = 2},
{x = 0, y = 16},
{x = 16, y = 0},
{x = 0, y = 0}}
```
the first offset in this example is targeting an almost cardinal direction which would likely result in a crash from the first bug, the offset of (0, 0) is targeting the caster and would result in being asked if you wanted to target yourself (but only if processing earlier offsets didn't crash). If you happened to get no offsets that caused a crash, some of the bolts could still be shoot out in similar directions looking like there were bolts missing.

**Comment by Implojin** [comment] 2024-12-04 08:28
Just to add to the datapoints here, I could not get this to reproduce while running a native, fully-updated manjaro with the 6.12 kernel and a standard `make TILES=y` build of 0.32.1, using the provided save.

I'm left strongly wondering whether this is being caused by an improper build of that arch crawl-tiles package, somehow.

**Comment by WizardIke** [comment] 2024-12-04 08:34
I also wasn't able to reproduce when building myself although My exact gcc version might not have matched

**Comment by WizardIke** [comment] 2024-12-04 08:46
I was also able to reproduce it easily without the provided save file on the prebuilt crawl-tiles package

**Comment by van9k** [comment] 2024-12-04 08:54
I'm not that familiar with c and difference between running prebuild package or build from source. Since the problem, most likely, is in the way manjaro/arch maintainers had build crawl-tiles, i should address bugreport to their forums so they can provide enviroment which may lead to clues that solve that problem? Haven't reproduce bug in vanilla Arch, but since manjaro is based on it, their package might be origin of bug.

**Comment by heftig** [comment] 2024-12-04 14:34
Proper traces might be helpful. Arch Linux provides debuginfo using debuginfod.

If it's an abort in C++ code, my guess is this is a failing bounds check, added by compiling with `-Wp,-D_GLIBCXX_ASSERTIONS`.

**Comment by heftig** [comment] 2024-12-04 14:47
It's not a stdlib assertion but Crawl's own assertion:

```
ASSERT(in_non_diamond_int(r.start)) in 'ray.cc' at line 220 failed.
```

Attempting to cast starburst in crawl-ncurses from the provided ttt.cs crashes. Here's my own crash dump, which contains a detailed trace from GDB:

[crash-ttt-20241204-154349.txt](https://github.com/user-attachments/files/18009967/crash-ttt-20241204-154349.txt)

**Comment by heftig** [comment] 2024-12-04 22:54
Looks like it was some sort of miscompilation with LTO and mixed optimization flags. Our build injects a bunch of flags via `EXTERNAL_FLAGS` and `EXTERNAL_LDFLAGS`.

Building like this reproduces the bug:

```
make EXTERNAL_FLAGS=-O2 LTO=y NO_TRY_GOLD=y NO_TRY_LLD=y TILES=y all
```

Because of #4156, `CFOPTIMIZE` is set to `-O0`. For object files, the `EXTERNAL_FLAGS` override this with `-O2`. But during the LTO link, the inherited `-O2` is again overridden with `-O0`. It looks like this produces broken code.

I've added `CFOPTIMIZE=` to our builds to remove the extra optimization flags and it seems to be fixed.

**Closed** 2024-12-06 20:56 UTC
