### ISSUE TITLE
Felid dying in labyrinth can rob more branches

### ISSUE THREAD

**Issue by caryoscelus** [crawl/crawl#4067] opened 2024-09-30 11:26 UTC
**PLATFORM and OS or BROWSER:**
local console / nixos

**DCSS VERSION AND GAME INFORMATION:**
0.32, 0.33-a0-151-g9ec8a70d

**DESCRIPTION:**
get felid character to die to minotaur in labyrinth and they can teleport to initial zone and thus can clear another branch (even though they have already cleared one of the branches). i understand this might be tricky to fix (especially unclear how to deal with edge cases where you have robbed one branch, but haven't really cleared it of monsters)

**Comment by kleiner-fisch** [comment] 2024-10-09 03:15
In general, on revival Felids are teleported to a safe area.

When dying in a labyrinth I could think of these solutions:

1. Revival outside the labyrinth. 
1. Revival in Minotaur area (cannot go back to looting area)
1. If died in looting area, revival in looting area (safe area before the last looting room you entered). 

With Option 3 I see the potential problem that the next room might simply be too hard. Then you are forced to lose all your lives there, which would be very frustrating.

I would think that Option 1 and Option 2 are the best options. And there the behavior should be consistent with the behavior of other caves. E.g. in the Ice Cave, are Felids revived outside the cave, or inside?  

@caryoscelus What do you think?

I would like to work on this.

**Comment by caryoscelus** [comment] 2024-10-11 12:25
@kleiner-fisch i think ideal solution (however might be more complicated to implement, dunno) would be to simply lock/disable transporter(s) leading to all unselected branches. and then reviving in starting area in all cases would work just fine, without putting you into unnecessary danger nor allowing to loot too much

**Comment by gammafunk** [comment] 2024-10-11 15:09
I would classify this aspect of felids as a feature, not a bug. Felids are permitted to use their lives in calculated gambles in order to obtain some gain, either short of long term. More typical situations would have a felid player deciding whether to try to use their limited consumables to escape death versus spending a life and saving those consumables for when they're more likely to be successful. In a Gauntlet, you're taking on a bunch of additional hard fights after spending a life to take another path, and you're fighting a difficult monster at the end where you might actually need that extra life.

Just to be sure, I did ask the others devs whether felids choosing to spend lives in a Gauntlet seemed problematic, but there was agreement that it's not. Hence I'm closing this issue as won't fix.

**Closed by gammafunk** 2024-10-11 15:09 UTC

**Comment by gammafunk** [comment] 2024-10-11 16:45
> just to clarify it wasn't about choosing to spend lives for me. i just had a character die and noticed an opportunity to loot more (and the fights in alternative branches aren't always hard for every character)

Yes, sometimes the player won't actively make this decision ahead of time, but that's also an aspect of felids. Inadvertently discovering new and novel ways to spend extra lives is part of the fun of playing this species. As for the other path being easy, as mentioned, you don't know exactly how easy the minotaur fight will be, and being down an extra life could matter. Sometimes alternatives will be (or seem) relatively easy, and that's part of the variance in a game like this.

> i can understand your decision, but i think it would be more informational (for any people who may find this worth of an issue) to explicitly close the issue with "not planned" sign rather than "completed"

Here "completed" just means "closed". That description can't be changed, but I've added a label of "wontfix" to clarify, thanks.

**Comment by gammafunk** [comment] 2024-10-11 16:53
Yeah, I found the option for that in the dropdown, thanks.
