### ISSUE TITLE
Crash when pressing "\"

### ISSUE THREAD

**Issue by latteier** [crawl/crawl#3448] opened 2023-12-31 20:01 UTC
**PLATFORM and OS or BROWSER:**
Local tiles
Mac OS 14.2.1

**DCSS VERSION AND GAME INFORMATION:**
Dungeon Crawl Stone Soup 0.31-a0-1530-g330b8c2b23 (SDL Tiles)

**DESCRIPTION:**
Crash when I hit the backslash "\\" key.

**EXTRA FILES:**
[crash-Bipaper-20231231-114537.txt](https://github.com/crawl/crawl/files/13802103/crash-Bipaper-20231231-114537.txt)

**Comment by latteier** [comment] 2023-12-31 20:08
BTW, I can reproduce this. Start a game, hit "\" and I get a crash.

**Comment by PleasingFungus** [comment] 2024-01-07 06:56
Thanks for reporting! This is a duplicate of #3404 and is fixed by bec6b6ccbf. Cheers!

**Closed by PleasingFungus** 2024-01-07 06:56 UTC
