### ISSUE TITLE
Lemures of Pikel do not disappear after shapeshifted Pikel dies

### ISSUE THREAD

**Issue by projectNoob** [crawl/crawl#3226] opened 2023-08-03 06:57 UTC
**PLATFORM and OS or BROWSER:**

webtiles on kelbi.

**DCSS VERSION AND GAME INFORMATION:**

0.30.

**DESCRIPTION:**

I was playing a OgCK. Xom shapeshifted Pikel, then I killed Pikel, but the lemures didn't disappear.

**EXTRA FILES:**

<img width="533" alt="Screenshot 2023-08-03 145443" src="https://github.com/crawl/crawl/assets/82269729/cd5ff30f-4f36-4935-919d-5ab05ea7b67e">

**Comment by PleasingFungus** [comment] 2023-08-04 17:25
Tentatively calling this a duplicate of #1861. Thanks for reporting!

**Closed by PleasingFungus** 2023-08-04 17:25 UTC
