### ISSUE TITLE
Shoals_end_hellmonk_lost_city always partially explored

### ISSUE THREAD

**Issue by dillytin** [crawl/crawl#2344] opened 2022-01-10 05:55 UTC
**DCSS VERSION AND GAME INFORMATION:**
0.28-1435-g8239
(this bug has been a while)

**DESCRIPTION:**

Shoals_end_hellmonk_lost_city can't be fully explored ever. It seems that it's related to open sea border of the map. Ashenzari's map detection reaches beyond the border of the map. Moreover, if you use mapping as a wizmode command, you can finally be done with exploring.

**EXTRA FILES:**

![캡처](https://user-images.githubusercontent.com/65288602/148720590-98637589-ff5c-4775-a5f2-9d2a6d62fc7a.PNG)
![캡처2](https://user-images.githubusercontent.com/65288602/148720592-59e194df-d4a1-4ac2-978d-cc73f643d932.PNG)
![image](https://user-images.githubusercontent.com/65288602/148723381-ee686c0a-34f5-4437-b8cf-cbde673d3b07.png)

**Comment by PleasingFungus** [comment] 2024-01-07 23:43
(i spent a while looking into this when it was first reported but couldn't fix it. We still should, though.)

**Comment by DracoOmega** [comment] 2024-11-24 02:56
I can no longer reproduce this. Possibly due to how Ashenzari scrying has changed in the meantime, or possibly because of something else, but I'm going to go ahead and close it.

**Closed by DracoOmega** 2024-11-24 02:56 UTC
Labels: vaults
