### ISSUE TITLE
Trunk crashes when traveling

### ISSUE THREAD

**Issue by alistairmk** [crawl/crawl#4160] opened 2024-12-06 02:57 UTC
**PLATFORM and OS or BROWSER:**
 Webtiles; Mac Firefox

**DCSS VERSION AND GAME INFORMATION:**
0.33-a0-540-gceed6161e0; Game started: 0.33-a0-520-g0c05a917f8

**DESCRIPTION:**
Crashing when I try to [G]o someplace or Ctrl-F travel. Shift-X also causes a crash when I try to escape out from it, or return to go to stairs. I can take one step at a time with movement keys, and I can use x, move cursor, then return to travel several steps without crashing. Had no problems until tonight. Had just cleared out Zot 5.

**EXTRA FILES:**
[Crashlog-Morgue.zip](https://github.com/user-attachments/files/18032171/Crashlog-Morgue.zip)
Save: https://crawl.dcss.io/saves/Twinkles-crawl-git-ceed6161e0-241206-0312.tar.bz2

**Comment by Implojin** [comment] 2024-12-07 17:03
This was being caused by 761acde7cb and should have been fixed by 8bf3021b3d. Thanks for the bug report!

**Closed by Implojin** 2024-12-07 17:03 UTC
