### ISSUE TITLE
Harold hex wand percentage not shown

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#2014] opened 2021-07-03 23:36 UTC
**PLATFORM and OS or BROWSER:**
webtiles 0.27-a0-1434-g6f15984924

**DESCRIPTION:**
The chance to succeed for hex wanding Harold is not shown. I tried with poly and para. There's an existing issue that was closed in Dec 2020. #1287 It was closed because Wheals couldn't reproduce it. I'll post the morgue after the game ends. 

**EXTRA FILES:**
![image](https://user-images.githubusercontent.com/70080435/124369028-70df6c80-dc35-11eb-9e0b-85033c924707.png)

**Comment by ardl** [comment] 2021-07-06 21:27
https://cbro.berotato.org/morgue/runninginthe90s/morgue-runninginthe90s-20210705-220723.txt

**Comment by rawlins** [comment] 2021-07-21 21:24
I can't reproduce this either, but I guess I won't close it. I think the screenshot is not what was intended? Doesn't seem to show a wand targeter.

**Comment by ardl** [comment] 2022-04-30 15:31
Pleasingfungus said quivering nets was causing the problem. see here: https://discord.com/channels/205277826788622337/205316046230388737/969982273367703593
also 
![image](https://user-images.githubusercontent.com/70080435/166112055-1831b843-4e3c-4b4d-a276-533ddf2b074c.png)

**Comment by rawlins** [comment] 2022-04-30 16:18
I'm not sure if this was your original problem since I can't find it in your current rcs, but I was able to replicate this with the following lines from particleface's rc:

```
msc := message_colour
msc += mute:Throwing.*\:
```

For example, this will mute the following line, because of the later `:`:

```
Aim: Harold, wielding a +0 scimitar, wearing a +0 ring mail and quivering a
 throwing net (chance to affect: 17%)
```

(Sounds like this is coming from hda.rc, so may be a widespread problem, but, not a bug!)

**Comment by rawlins** [comment] 2022-04-30 17:15
Alright after some discussion this was indeed also ardl's problem, so I'm going to close it up.

**Closed by rawlins** 2022-04-30 17:15 UTC
Labels: bug, ui
