### ISSUE TITLE
OS X dotfiles in archives cause errors when compiling

### ISSUE THREAD

**Issue by kitchen-ace** [crawl/crawl#1486] opened 2020-07-12 20:27 UTC
**PLATFORM and OS or BROWSER:** Arch Linux local tiles

**DCSS VERSION:** 0.25.0

OS X cache/dotfiles (unsure of the right name) are present in the stone_soup-0.25.0.tar.xz and stone_soup-0.25.0-nodeps.tar.xz archives at https://crawl.develz.org/release/0.25/ . Compiling without removing these files produces errors, e.g. 

`stone_soup-0.25.0/source/dat/des/arrival/._simple.des:1: syntax error`

The source code archive https://github.com/crawl/crawl/archive/0.25.0.tar.gz at http://crawl.develz.org/download.htm doesn't have these files. I didn't test any other archives.

**Comment by rawlins** [comment] 2020-07-17 17:37
This problem seems to have been simply caused by generating the xz files on mac -- I was never able to even see the dot files locally, let alone remove them, though another dev confirmed their existence. So I guess the resolution is that we can't do that any more. For 0.25.1 I generated them on linux while building the debs; the 0.25.1 nodeps package is now uploaded here and shouldn't have this issue: https://github.com/crawl/crawl/releases/tag/0.25.1

If someone really needs it we can probably re-generate the 0.25.0 archives without those, feel free to ping me, but I'm going to go ahead and close this issue.

**Closed by rawlins** 2020-07-17 17:37 UTC

**Comment by kitchen-ace** [comment] 2020-07-25 02:59
@rawlins I forgot to ask before - are the nodeps source packages going to be available on github going forward? Thanks!

**Comment by rawlins** [comment] 2020-07-25 03:24
> are the nodeps source packages going to be available on github going forward (i.e. is it safe for Linux package maintainers to update the source URL)?

Yes, I think so -- in general github release tags will be the primary download since the builds get generated by CI. Nodeps isn't currently part of this but we will sooner or later probably nodeps them to what gets autogenerated on a release, and for now we will plan to upload them to the release tag after generating debs (they are built as part of that process). We may still mirror them on CDO, though obviously that hasn't been done yet for 0.25.1.
