### ISSUE TITLE
Game Crashed Upon Create Descent Character

### ISSUE THREAD

**Issue by kleiner-fisch** [crawl/crawl#4161] opened 2024-12-06 03:42 UTC
### Version:
- Webtiles, browser: brave
- Version: Dungeon Crawl Stone Soup 0.33-a0-540-gceed6161e0

### DESCRIPTION:

Created a **descent** Demonspawn Monk. The game crashed before I could make my first move.

The same happened again, when I created a **descent** Felid Berserker.

After the crash I was able to load the game again. I can make a move, but the game crashes immediately. If I then load the game again, the move is done, but the time is not updated (still time is at 0, even though I am not at the starting position anymore).  
#### First Game (Demonspawn Monk) 
- First crash report:  [crash-sefie-20241206-030153.txt](https://github.com/user-attachments/files/18032214/crash-sefie-20241206-030153.txt)
- Second crash report (after loading the game after first crash):  [crash-sefie-20241206-031339.txt](https://github.com/user-attachments/files/18032271/crash-sefie-20241206-031339.txt)

#### Second Game (Felid Berserker)
[crash-sefie-20241206-031903.txt](https://github.com/user-attachments/files/18032419/crash-sefie-20241206-031903.txt)

**Comment by Implojin** [comment] 2024-12-07 16:58
This was being caused by 761acde7cb and should have been fixed by 8bf3021b3d. Thanks for the bug report!

**Closed by Implojin** 2024-12-07 16:58 UTC
