### ISSUE TITLE
Merfolk in statue form fails to attack in deep water

### ISSUE THREAD

**Issue by DevastatorOne** [crawl/crawl#3175] opened 2023-06-28 08:42 UTC
**PLATFORM and OS or BROWSER:**
Local tiles, Windows 10

**DCSS VERSION AND GAME INFORMATION:**
0.30

**DESCRIPTION:**
Merfolk in statue form keeps racial bonuses (extra EV and move speed) while in deep water but "fumble to attack". This feels very weird.

**EXTRA FILES:**
![1](https://github.com/crawl/crawl/assets/81159762/6dcc3078-e27b-49c9-841a-15469feaf84c)
![2](https://github.com/crawl/crawl/assets/81159762/f5709f36-af4c-4b3a-8d5d-be45b38e53ad)
![3](https://github.com/crawl/crawl/assets/81159762/9cf45361-7e1e-4d1f-a1df-ccb1c4e0791b)
![4](https://github.com/crawl/crawl/assets/81159762/84867926-b24c-4a87-bf68-ccf6b312d720)
![5](https://github.com/crawl/crawl/assets/81159762/d01f8287-6594-4e0b-a898-d5f582cb03ec)

**Comment by orjb1** [comment] 2023-07-14 08:42
Semi-Duplicate of issue  #3081

explanation on linked issue is great :)

**Comment by PleasingFungus** [comment] 2023-08-04 17:28
Closing as duplicate of #3081. Thanks for reporting!

**Closed by PleasingFungus** 2023-08-04 17:28 UTC
