### ISSUE TITLE
The lookup information says monsters can drain djinn's magic

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#2570] opened 2022-06-12 09:39 UTC
**PLATFORM and OS or BROWSER:**
Linux 3.16.0 console using XTerm(358)

**DCSS VERSION AND GAME INFORMATION:**
0.29-a0-575-g0dc89cf053

**DESCRIPTION:**
If I start a djinni and look at the monster descriptions (e.g. ?/m with the default keymap), the descriptions for great orb of eyes say that their SPELL_DRAIN_MAGIC has an effect, as does the one for ghost moths' SPELL_DRAINING_GAZE.

I would expect it to say that neither has an effect. MUT_HP_CASTING means djinn never have any magic points to drain.

EXTRA FILES:

None

**Comment by PleasingFungus** [comment] 2022-07-16 04:13
I don't understand what you mean by "the descriptions say their SPELL_DRAIN_MAGIC has an effect", or "I would expect it to say that neither has an effect". Where, exactly, does it say this? I just see this UI:

![image](https://user-images.githubusercontent.com/1192475/179338792-2dc357d1-42d8-4dea-8bba-bda75a6475f3.png)
![image](https://user-images.githubusercontent.com/1192475/179338794-b36465c4-0588-4cf2-b70a-07ea452fca59.png)

Which says nothing about whether the spells work on you, the player, or not. Is this a complaint about the displayed resist chance?

**Comment by rawlins** [comment] 2022-08-09 03:16
I'm guessing it's either the % chance, or that this might be about the description of the spells accessible via the monster description:

<img width="754" alt="Screen Shot 2022-08-08 at 11 12 05 PM" src="https://user-images.githubusercontent.com/6290753/183555545-a980d5fd-4a5e-47fd-b4f8-84e145371618.png">

But, these descriptions currently don't have any dynamic content and this description is accurate w.r.t. djinni. I think there's probably a PRable FR here but maybe not a bug, so I'm going to close this.

**Closed by rawlins** 2022-08-09 03:16 UTC
Labels: ui
