### ISSUE TITLE
Filename error in Turkish locale

### ISSUE THREAD

**Issue by jfcg** [crawl/crawl#846] opened 2018-09-05 18:14 UTC
**PLATFORM:**
Manjaro XFCE Desktop Linux 64-bit, kernel 4.14.67
System language is Turkish.

**VERSION:**
0.22.0-1 from Manajaro repository

**DESCRIPTION:**
 When I start Dungeon Crawl Stone Soup, I get the following error. I noticed Turkish lower case I's in the message and thought it is about some locale problem.
CC: @schuay

![stone-shot](https://user-images.githubusercontent.com/1410597/45112438-42bd4380-b150-11e8-907b-e03bf194b1a4.jpg)

**Comment by rawlins** [comment] 2018-09-05 19:19
Could you provide the output of running `locale` at the command line? Is there anything else suspicious in the log when you hit ctrl-p? Also, do you know if this is a new problem with 0.22? Thanks.

**Comment by rawlins** [comment] 2018-09-05 20:36
Yes, this looks like a locale problem, a localized version of `towlower` (at least under some build conditions) is being used for generating filenames, where the lowercase version of `I` in Turkish is not `i`.

This will need someone who can replicate the problem to do the fix (which so far isn't me; it's either OS-dependent or compiler-dependent or both).  This is somewhat speculative since I can't replicate it, but in the meantime if you manually set the locale from the command line (maybe `export LC_ALL="en_US.UTF-8"`) you should hopefully be able to run the game from the command line in that shell. We don't have any Turkish localization for game content, so you won't be missing out on too much by doing that I think.

**Comment by jfcg** [comment] 2018-09-05 20:42
LC_ALL trick on cli worked. indeed it is a locale problem. thx

**Comment by rawlins** [comment] 2018-10-20 13:40
This is still waiting on someone who can replicate a version of this to actually fix; one suggestion from @neilmoore was just to use our libutil.h:toalower, which shouldn't be locale-sensitive, but I'm wary of doing that without being able to test it.

**Comment by rawlins** [comment] 2019-06-19 18:38
I spent a bit more time working on this because I've been working on locale issues in general; I was finally able to reproduce it in linux in a docker container. Unfortunately it's not just the immediate crash that presents itself here, but really basically every `lowercase` and `tolower`, as well as many `toupper` calls that cause problems for this locale (as long as at least one piece of data has `I` or even `i`). Possibly all or most of these should be switched to be locale-insensitive, since they mostly have to do with internal data, but I suspect doing this will break some existing localizations, because this distinction isn't very clean in the code. Once you start converting these calls, you more or less have to convert all of them (I have a partial implementation that takes this strategy). So it's a bit unclear to me what the next steps are...

**Comment by rawlins** [comment] 2019-06-21 13:59
This is resolved in bf76ec32ab3c by generally preventing casing changes from ever affecting ASCII characters. I still don't know how this might impact a Turkish keyboard layout, but crawl now works with the `tr_TR.utf8` locale and that commit doesn't seem to have generated other problems so far, so I'm going to go ahead and close this.

**Closed by rawlins** 2019-06-21 13:59 UTC
Labels: bug, help wanted
