### ISSUE TITLE
Game crashing a lot. Can replicate with swamp drakes

### ISSUE THREAD

**Issue by WizardIke** [crawl/crawl#3464] opened 2024-01-06 09:01 UTC
**PLATFORM and OS or BROWSER:**

CPO webtiles

**DCSS VERSION AND GAME INFORMATION:**

version 0.31-a0-1591-g515db51

**DESCRIPTION:**

The game is crashing mainly in Elf but it did crash twice in the same spot on the Lair:5 ending. I could replicate a crash offline but only in a debug build. To replicate I surrounded myself with swamp drakes and another creature (I tested both goblins and kobolds), after a few turns the game crashed.

**EXTRA FILES:**

Here are some of the crash logs
https://crawl.project357.org/morgue/Wizard1ke/crash-Wizard1ke-20240106-075759.txt
https://crawl.project357.org/morgue/Wizard1ke/crash-Wizard1ke-20240106-073435.txt
https://crawl.project357.org/morgue/Wizard1ke/crash-Wizard1ke-20240106-062907.txt
https://crawl.project357.org/morgue/Wizard1ke/crash-Wizard1ke-20240106-062316.txt

**Comment by PleasingFungus** [comment] 2024-01-07 05:59
This was caused by 5eddcf24482227776da4f91a11eaaacfad401233 and fixed in ea8d8529529938644a229dc4ba066fb95c7b3b4e/e08a94be7c24a9bf3c6c621e59f43344ab990ed1. Thanks for reporting!

**Closed by PleasingFungus** 2024-01-07 05:59 UTC
