### ISSUE TITLE
Screen size-related crash when using <> in X mode

### ISSUE THREAD

**Issue by Etesian** [crawl/crawl#1166] opened 2019-10-03 18:12 UTC
Local tiles, windows 10, version

 0.24-a0-760-g74cc3ae

Using <> to locate stairs in X mode can cause crashes, but ONLY in maximized window. Unsure of the exact conditions, but [here's](https://www.sendspace.com/file/4inh39) a save file on which it is consistent.

Thanks!

**Comment by Etesian** [comment] 2019-10-03 18:33
Update: here's another save, turns out it's not necessarily fullscreen. [Here](https://www.sendspace.com/file/qi0z2e)'s a save where it crashes in 2 circumstances:
1) as soon as I enter X mode when not fullscreen (unsure of exact resolution, I only have tile_full_screen=false in my init file)
2) fullscreen lets me enter X mode, but crashes as soon as I press >

**Comment by alexjurkiewicz** [comment] 2019-10-03 19:31
Do you have any custom RC file or are you launching with any custom parameters? I'm wondering if pregen is enabled

**Comment by rawlins** [comment] 2019-10-03 20:03
I don't think pregen is involved (maybe @alexjurkiewicz is thinking of [], not <>) but it would be useful to know more system details; I can't reproduce this in a windows 10 vm with this exact crawl version and these saves. Does the crashlog found in the morgue directory have any information? (It's usually pretty sparse on win10, but there may be an ASSERT in the first line that would be informative.)

(Also, if you need to upload any more files, can you try uploading them as a zipped version via github itself?)

**Comment by rawlins** [comment] 2019-10-03 20:05
Also, what happens if you set `tile_map_scale = 1.0`?

**Comment by Etesian** [comment] 2019-10-04 09:15
Tried with both my normal RC/init file and the default; doesn't change anything, neither does adding tile_map_scale = 1.0.
Didn't know that's where the crashlogs are, here
[crash-Etesian-20191004-111154.txt](https://github.com/crawl/crawl/files/3689791/crash-Etesian-20191004-111154.txt)

(Yeah sorry, didn't think of trying zips after seeing github dislikes both the savefile format and .rar)

**Comment by aidanholm** [comment] 2019-10-06 21:19
Thanks for reporting; this should be fixed at bb1ff42f1e.

**Closed by aidanholm** 2019-10-06 21:19 UTC
