### ISSUE TITLE
Shift+L Click drops items inscribed with {!d}

### ISSUE THREAD

**Issue by dessaya** [crawl/crawl#985] opened 2019-02-11 02:43 UTC
**PLATFORM:**
local tiles, tested on Linux

**VERSION:**
0.22.1

**DESCRIPTION:**
* Inscribe an item with {!d}
* Shift+L Click the item. It is dropped with no prompt.

**Comment by alexjurkiewicz** [comment] 2019-02-11 02:50
Isn't this a duplicate of #898?

**Comment by dessaya** [comment] 2019-02-11 03:31
I don't think so. They could be related but my guess is that #898 seems like a bug related to SDL and handling of key modifiers after the window loses focus; while this one seems more close to game logic: Shift+L Click triggers the Drop action, but using an incorrect path in which it skips the !d prompt.

**Closed** 2022-08-11 16:28 UTC
Labels: bug, ui, tiles
