### ISSUE TITLE
Casting Beastly Appendage as an Octopode melds hat even though its a tentacle spike

### ISSUE THREAD

**Issue by vimuston** [crawl/crawl#2778] opened 2022-10-11 19:21 UTC
While transformed, auxiliary armour on the **affected body parts** is melded. 

It shouldn't affect that hat I think?

**Comment by vimuston** [comment] 2022-10-11 19:22
_One of your tentacles grows a vicious spike.
 Your +0 hat melds into your body._

**Comment by dillytin** [comment] 2022-10-12 03:39
#1699 already dealt with this, which confirmed that it is intended.

**Comment by kd7uiy** [comment] 2022-10-12 13:03
At the very least maybe we should have the text say growing out of its head? I'm not sure I understand why no headbutt either, but...

**Comment by semitonal** [comment] 2023-01-22 16:39
Closing, see also #2919 (the description of the spell has been updated to clarify).

**Closed by semitonal** 2023-01-22 16:39 UTC
