### ISSUE TITLE
Local tiles not centered when using Wayland

### ISSUE THREAD

**Issue by randomMesh** [crawl/crawl#2181] opened 2021-10-11 07:56 UTC
**PLATFORM and OS or BROWSER:**
Local tiles, Ubuntu 21.04 aarch64, Wayland

**DCSS VERSION AND GAME INFORMATION:**
```
Crawl version 0.28-a0-643-g84cb2ea78e
Save file version 34.236
Compiled with GCC 10.3.0
Build platform: aarch64-linux-gnu
Platform: aarch64-linux-gnu
CFLAGS: -O2 -pipe -DUSE_TILE -DUSE_TILE_LOCAL -DUSE_SDL -DUSE_GL -DUSE_FT -D_REENTRANT -Wall -Wformat-security -Wundef -Wextra -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-type-limits -Wno-uninitialized -Wno-array-bounds -Wno-format-zero-length -Wmissing-declarations -Wredundant-decls -Wno-parentheses -Wwrite-strings -Wshadow -pedantic -Wuninitialized -Iutil -I. -isystem /usr/include/lua5.1 -isystem /usr/include/freetype2 -I/usr/include/libpng16 -isystem /usr/include/SDL2 -DWIZARD -DASSERTS -DPROPORTIONAL_FONT="/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf" -DMONOSPACED_FONT="/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf" -D_REENTRANT -DCLUA_BINDINGS
LDFLAGS: -rdynamic -fuse-ld=gold -O2
```

**DESCRIPTION:**
Ubuntu 21.04 uses Wayland rather than X.Org as a default and Crawl fails to center its window under it. It's a bit off to the left.
See screenshot:

![crawl_wayland](https://user-images.githubusercontent.com/32773707/136753150-14abb832-9333-4ab3-9282-62c2862cb18c.png)

Switching to fullscreen mode solves the problem, all is nicely centered but unfortunately, there is a [Wayland bug](https://www.reddit.com/r/openSUSE/comments/n82w5g/invisible_mouse_cursor_in_fullscreen_games_under/) which makes the mouse cursor disappear sometimes in fullscreen apps.

**Comment by 1player** [comment] 2022-08-31 15:20
Can't reproduce on master, GNOME/Wayland. It's probably been fixed since.

**Comment by rawlins** [comment] 2022-08-31 15:38
Thanks, I'll go ahead and close. (Not sure we made any changes that would directly address this, but maybe it was fixed on the gnome/wayland side.)

**Closed by rawlins** 2022-08-31 15:38 UTC
