### ISSUE TITLE
Plasma Beam hits invisible monsters even without a silhouette 

### ISSUE THREAD

**Issue by Steveneveneven** [crawl/crawl#3119] opened 2023-05-05 04:51 UTC
**PLATFORM and OS or BROWSER:**
Webtiles

**DCSS VERSION AND GAME INFORMATION:**
.30-b1-5-g8e6c1be

**DESCRIPTION:**
Plasma beam no longer draws a line between you and invisible monsters but it still hits them, even without a silhouette. It is reproducable and nothing else of note was happening when this issue occurred

**EXTRA FILES:**
![image](https://user-images.githubusercontent.com/132639558/236379855-e4899501-eb26-4ed8-bc80-02c99af930a0.png)
![image](https://user-images.githubusercontent.com/132639558/236379866-99f1055a-d085-42a5-a7fc-1e4a61eb2f4a.png)

**Comment by Implojin** [comment] 2023-05-05 05:42
I was able to reproduce this in trunk (vs. an unseen horror) by casting Plasma Beam at the character's location:

The targeting cursor doesn't overtly reveal the unseen horror's position, but if you attempt to cast while targeting the player's position, the spell successfully casts anyway, firing at the nearby unseen horror.

**Comment by semitonal** [comment] 2023-05-23 16:33
I could certainly see an argument for having it ignore invisible monsters entirely but I think this is working as intended - it's supposed to be able to hit invisible monsters if they happen to be around, just not to reveal their presence if you don't know about them. (Hopefully this will be fully resolved by #3017 at some point, too).

**Closed by semitonal** 2023-05-23 16:33 UTC
Labels: bug
