### ISSUE TITLE
on view of mutaition, it shows only 1 demonspawn mutation.

### ISSUE THREAD

**Issue by heeroduo** [crawl/crawl#841] opened 2018-08-15 08:20 UTC
When reporting a bug, please include the following:

**PLATFORM:**
local tiles, Mac version

**VERSION:**
0.22

**DESCRIPTION:**

First, it's normal mutations. we can see all of description of mutaition on each lines.
<img width="604" alt="retina1" src="https://user-images.githubusercontent.com/10691965/44618847-52b36880-a8b0-11e8-9215-e7040c8769f4.png">

And it's just 1 demonspawn mutation. It looks OK.
<img width="525" alt="retina2" src="https://user-images.githubusercontent.com/10691965/44618854-6232b180-a8b0-11e8-8f75-d12976750cf7.png">

But when I get more demonspawn mutations, It is not be shown and we can see that there is ....
<img width="534" alt="retina3" src="https://user-images.githubusercontent.com/10691965/44618857-6eb70a00-a8b0-11e8-93b8-c38d480db8e5.png">

It means that these sentences are combined I think. I mean, maybe there is no code for starting on new lines after add sentence for description like '/n' lol hahaha

Please check it. It's 22 version for Mac. I love DCSS. 

PS. please add Slime as species lol

[@aidanholm edit: inlined pictures]

**Comment by laSinteZ** [comment] 2018-08-24 12:51
Same problem here. Can't see full mutations text. Simple example is minotaur: only 1 mutation is shown. Local tiles, 0.22, macOS. Can I disable text truncation somehow? Couldn't find this option.

<img width="761" alt="screen shot 2018-08-24 at 15 50 27" src="https://user-images.githubusercontent.com/10958990/44585566-7776e580-a7b5-11e8-952c-feb1c3b86e70.png">
<img width="561" alt="screen shot 2018-08-24 at 15 50 36" src="https://user-images.githubusercontent.com/10958990/44585568-7776e580-a7b5-11e8-8bb8-a286ba2aa363.png">

**Comment by laSinteZ** [comment] 2018-08-25 15:44
@aidanholm most probably you are right, I am running DCSS on Macbook Pro (So resolution is 1440x900, real is 2560 × 1600, default resolution for Macbook).

**Comment by rawlins** [comment] 2018-08-25 20:33
Yes, I was also seeing this on a macbook pro, so I can probably reproduce it enough to look into.

**Comment by laSinteZ** [comment] 2018-09-25 07:52
This issue seems to be resolved in `0.22.1`
Thanks for this fix, I can play Dungeon Crawl again :)

**Closed** 2018-09-28 14:59 UTC

**Comment by rawlins** [comment] 2018-09-28 15:50
oh, yeah I fixed this in 456867d837b662a49, sorry for not updating this issue.
