### ISSUE TITLE
'<' and '>' Confusingly shown when swapping rings

### ISSUE THREAD

**Issue by ukdong90** [crawl/crawl#1834] opened 2021-03-17 05:48 UTC
**DCSS VERSION AND GAME INFORMATION:**
0.27-a0-604-g29a88b33a7

**DESCRIPTION:**
![unknown](https://user-images.githubusercontent.com/65288602/111420983-8afd4980-872f-11eb-8fce-d6835b592c9d.png)

'>' is prompted first, and then '<' comes after it, which is intuitively confusing(look at the keyboard and then you know what I'm saying)

![unknown (1)](https://user-images.githubusercontent.com/65288602/111420996-905a9400-872f-11eb-8f94-e28b11739ec1.png)

this is from 0.24, which makes more sense

**Comment by Goratrix** [comment] 2021-03-18 15:17
Duplicate issue also here: https://github.com/crawl/crawl/issues/1819

This is caused by efe1b44 and f99593c, after which the right finger is considered as 'first' for various purposes instead of left one. However internally in the code left is still considered 'first' in many places, and the < > key assignment also was more intuitive in this regard.

I suppose the best way would be to revert and go back to left finger being considered the 'first' so that the < > assignment corresponds to the physical hands again?

**Comment by Goratrix** [comment] 2021-03-26 19:23
Fixed/reverted now with a16a6a3, thanks advil!

**Comment by rawlins** [comment] 2021-03-26 19:25
Sorry, yeah, should have tagged this issue too. Should be fixed, thanks for the report!

**Closed by rawlins** 2021-03-26 19:25 UTC
