### ISSUE TITLE
Stats not going up with 0.28 Gnoll

### ISSUE THREAD

**Issue by ASilver** [crawl/crawl#2393] opened 2022-01-31 18:43 UTC
**PLATFORM and OS or BROWSER:**
<webtiles - Chrome>

**DCSS VERSION AND GAME INFORMATION:**
<0.28 - https://cbro.berotato.org/morgue/AlmostDecent/morgue-AlmostDecent-20220131-170118.txt>

**DESCRIPTION:**
<I reached lvl14 as a Gnoll EE, and realized after I had died that my stats were way too low, with no items or conditions to affect them. I then remembered it had not asked me for my stat choices as I leveled up at all. I cannot see it in the morgue, as such info is not there, but the stats alone should tell the tale. at lvl14 they should be considerably higher, regardless of my choices.>

**EXTRA FILES:**
<Here is morgue again: https://cbro.berotato.org/morgue/AlmostDecent/morgue-AlmostDecent-20220131-170118.txt>

**Comment by ASilver** [comment] 2022-01-31 19:00
Ok, it is confirmed. At lvl3 I am offered the option to increase my attributes, but at lvl6, and beyond, no luck.
![no-upgrade](https://user-images.githubusercontent.com/3589847/151855809-b63e4fcd-1519-4676-86a1-af9a84c5cf5a.png)

**Comment by liammcd** [comment] 2022-01-31 19:03
The stat choices were moved to every 6 levels, you should have the option at lvl 3, 9, 15, etc..

**Comment by rawlins** [comment] 2022-01-31 19:07
Yes, I haven't run through the exact numbers to double check, but at XL14 you should have received a stat choice at xl3 and 9, and the total stats look in line with that. The amount you get per choice is doubled.

**Comment by rawlins** [comment] 2022-01-31 19:10
This is every species but demigods, here's the commit with the details: 03ef38a5c2cf. This'll be in the 0.28 changelog as well but I'm not sure if it is yet.

**Comment by ASilver** [comment] 2022-01-31 19:15
BTW, the changelog says Robin was slightly nerfed. I take it this was in reference to the skills, not the +12 mace he killed me with.

https://cbro.berotato.org/morgue/AlmostDecent/morgue-AlmostDecent-20220131-015115.txt

**Comment by ebering** [comment] 2022-01-31 20:38
@ASilver issues aren't the place for general game discussion and should be kept single topic. I'm closing this one since as reported it is not a bug.

Regarding Robin the nerf was regarding the monster base stats. Item generation can still high roll.

**Closed by ebering** 2022-01-31 20:38 UTC

**Comment by ASilver** [comment] 2022-01-31 21:20
@ebering The comment on Robin was meant as a joke, the rest was on-topic. Does this mean all classes were nerfed in regards to attributes? Other than demigods. This wasn't in the changelog, and I am trying to understand what it means, not argue its merits.

**Comment by rawlins** [comment] 2022-01-31 21:24
It's not really much (if anything) of a nerf in that you get the same amount total of attributes with a different timing, and the effect of a single point at the intermediate levels is pretty negligible. But yes, it applies to all species except demigods.
