### ISSUE TITLE
Game crashes when reading Scroll of Acquirement/getting gift from Okuwaru/opening Treasure Trove etc

### ISSUE THREAD

**Issue by kruegersp** [crawl/crawl#2864] opened 2022-12-06 19:34 UTC
**PLATFORM and OS or BROWSER:**
Local tiles on Andriod Phone

**DCSS VERSION AND GAME INFORMATION:**
0.29.1
Custom seed 20221207

**DESCRIPTION:**
Since the last update I've noticed my game has crashed occasionally when reading Scrolls of Acquirement or getting a gift from Okuwaru. Usually if I just reload the game I start a few turns back and can read the scroll or get the gift again and there is no problem. In this game I was trying to open a Treasure Trove and the game crashed like in the other cases. However no matter how many time I reload the game it still crashes.

**EXTRA FILES:**
Attached is the .cs file and crashlog.
[DcssBug.zip](https://github.com/crawl/crawl/files/10169750/DcssBug.zip)

**Comment by kd7uiy** [comment] 2022-12-07 14:22
Probably a dupe of #2714

**Comment by rawlins** [comment] 2023-01-29 15:40
Thanks for the report, yes, this looks like the same crash as #2714 and was fixed by #2806

**Closed by rawlins** 2023-01-29 15:40 UTC
