### ISSUE TITLE
Ossuary does not show timer messages

### ISSUE THREAD

**Issue by nojaa3** [crawl/crawl#2056] opened 2021-08-10 06:27 UTC
PLATFORM and  BROWSER
Webtiles Safari 13.1.2

0.27.0-1-g7a089689b8 on D:5.

Ossuary does not show any timer messages, but its invisible timer works normally.

https://underhound.eu/crawl/saves/nojaa-crawl-0.27-210810-0618.tar.bz2 
Save backup, the lack of messages can easily seen from the message log.

**Comment by rawlins** [comment] 2021-08-10 14:22
Thanks for the report, this is a duplicate of #1640 so I will close and copy the info there.

**Closed by rawlins** 2021-08-10 14:22 UTC
