### ISSUE TITLE
Hardcoded path to `%appdata%`

### ISSUE THREAD

**Issue by koutoftimer** [crawl/crawl#943] opened 2019-01-15 07:39 UTC
Platform: windows 7 x64 russian
Version: 0.22.1 (20180916)

Description:
1. I have used "Tiles+Console" installer from https://crawl.develz.org/download.htm 
2. I have checked "Install for all users"
3. On lauch, game tries to create save folder in `C:\Users\...` but russian windows version have different path: `C:\Пользователи\...`

Additional info:
I'm not sure that path `C:\Users` exists, at least explorer translates it to `C:\Пользователи` every time I type it. I was sure you have to use WinAPI to get `%appdata%` but I'm in doubt now. Have to check FS first.

**Comment by Moredread** [comment] 2019-01-18 02:55
Interesting, in the German version of Windows c:\Users still exists and the localized version is a link to that (c:\Benutzer). Is this different for your system?

Still getting the path via %appdata% or the equivalent for the documents folder would be preferable.

**Comment by rawlins** [comment] 2021-04-27 14:55
Following up on this to try to move it somewhere (in absence of a committer with more expertise in Russian locales coming along): crawl does use `CSIDL_APPDATA` to select the directory as @alexjurkiewicz alludes to: this should be equivalent to `%RoamingAppData%`. So I think the problem is unlikely to be on the dcss end here, though I don't really know what the problem might be. I'm going to close this given its age, but I'm happy to reopen if there's more activity or it turns out to be dcss-related.

Not sure if the original committer will see this after the time lag, but for anyone trying to resolve a similar problem in the future: it is possible for AppData-type paths to be incorrectly configured, so one test for this would be to create a new user account and see if the problem goes away. Alternatively, it should be possible to open a command prompt and type `set` to see what the relevant environment variables are. As to fixing this sort of issue, I'm not a windows expert but various sites generally recommend creating a new profile. Not sure if there's a better way.

**Closed by rawlins** 2021-04-27 14:55 UTC
Labels: bug, locale, windows
