### ISSUE TITLE
Hep Ancestor Reflected my OOD back into me blowing me up :( 

### ISSUE THREAD

**Issue by Shapermc** [crawl/crawl#1997] opened 2021-06-26 00:32 UTC
Dungeon Crawl Stone Soup version 0.27-a0-1312-g5cdb2b3542 (webtiles)
Windows Machine, running Chrome

I had cast Orb of Destruction (ood) at an enemy, that enemy died, and then my ancestor (in this case We'wha in the image) reflected the OOD back at me, causing a nice explosion. I'm not sure the synergy with this, but it hurt pretty bad considering I should be able to cast through my ancestor. 

![image](https://user-images.githubusercontent.com/80350699/123496021-ac51b980-d5eb-11eb-8129-2941e0450790.png)

This is currently an in-progress game with my DrCj, so I am posting my current dump here too. 

[reflectbugreport.txt](https://github.com/crawl/crawl/files/6719337/reflectbugreport.txt)

**Comment by ebering** [comment] 2021-07-25 19:20
This story makes a good preface for the Book of Dangerous Friends, now in trunk. Closing it as intended behavior.

**Closed by ebering** 2021-07-25 19:20 UTC
Labels: bug, gameplay
