### ISSUE TITLE
Game Crash on spell cast

### ISSUE THREAD

**Issue by mclanier** [crawl/crawl#4163] opened 2024-12-06 12:10 UTC
**PLATFORM and OS or BROWSER:**
webtiles, windows/chrome

**DCSS VERSION AND GAME INFORMATION:**

Version: Dungeon Crawl Stone Soup 0.33-a0-541-g8bf3021b3d
Platform: unix
Bits: 64
Game mode: normal
Tiles: online

**DESCRIPTION:**
Saw a hornet zombie and tried to burn it with Searing Ray. Game crashed. To verify, I reloaded, tried again, game crashed again. 

**EXTRA FILES:**
 [crash-Triskal-20241206-115956.txt](https://github.com/user-attachments/files/18037935/crash-Triskal-20241206-115956.txt)

**Comment by Implojin** [comment] 2024-12-07 16:54
This is a duplicate of #4162 and should already be fixed by f8f82a2dde, thank you for the bug report!

**Closed by Implojin** 2024-12-07 16:54 UTC
