### ISSUE TITLE
SDL build error on local tiles macos m1

### ISSUE THREAD

**Issue by erf** [crawl/crawl#2983] opened 2023-02-03 13:04 UTC
**PLATFORM and OS or BROWSER:**

local tiles on macos Ventura 13.1 on a Apple M1

**DCSS VERSION AND GAME INFORMATION:**

116ff8c4af

**DESCRIPTION:**

I'm not able to build now on macos.

When i run: `make -j4 TILES=y mac-app-tiles`

I get the following message:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C rltiles all ARCH=arm64-apple-darwin22.2.0 NO_PKGCONFIG=Yes TILES=y
  * If you experience any problems building Crawl, please take a second look
  * at INSTALL.md: the solution to your problem just might be in there!
    LINK crawl
ld64.lld: error: undefined symbol: _objc_msgSend$bytes
>>> referenced by contrib/install/arm64-apple-darwin22.2.0/lib/libSDL2_image.a(IMG_ImageIO.o):(symbol _Create_SDL_Surface_From_CGImage_Index+0x10c)

ld64.lld: error: undefined symbol: _objc_msgSend$autorelease
>>> referenced by contrib/install/arm64-apple-darwin22.2.0/lib/libSDL2_image.a(IMG_ImageIO.o):(symbol _Create_SDL_Surface_From_CGImage_Index+0x104)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [crawl] Error 1
```

**EXTRA FILES:**

**Comment by rawlins** [comment] 2023-02-05 15:09
We've had one report of this before and based on the pasted build output, I think the problem is the same. This is happening because of incompatibilities with your version of the llvm linker (e.g. `ld64.lld` which you have installed somehow and are using instead of the apple-provided linker from xcode build tools) and current xcode as of a few months ago. From what I understand if you want to keep using this linker, llvm needs to be updated somehow: https://github.com/llvm/llvm-project/issues/56034.

We last had this report around 10/22 and at the time there wasn't much to be done from the llvm end unless you want to run bleeding edge versions (from the above issue: "this is supported in LLVM @ HEAD, and will be in LLVM 16"), but a solution may be to try to update llvm. The recommended solution (/supported build method) though is to build with the xcode-provided linker rather than `ld64.lld`. (I'm going to close this because there's not much else we can do beyond recommending this.)

There was some discussion of this in the dev logs on 2022-10-26 and 2022-10-27 in case that is helpful, though I think I got the main points: http://crawl.akrasiac.org/logs/cheibriados/

**Closed by rawlins** 2023-02-05 15:09 UTC
