### ISSUE TITLE
Incorrect display of "Place" in console play after browsing level maps

### ISSUE THREAD

**Issue by borekl** [crawl/crawl#1406] opened 2020-05-15 06:18 UTC
PLATFORM
console on CUE, CKO

DCSS VERSION:
0.25-a0-1078-gea6e5d949a

DESCRIPTION:
Incorrect display of "Place", only in console game, spectators using webtiles see correct Place. I have tried both CUE and CKO public servers, both reliably replicate the issue

How to replicate:
* enter map (using shift+x)
* use [ or ] to go to different level than the current one
* exit the map (using ESC)
* now the "Place" on the main display shows the level you exited the map at, not the current level; this incorrect information remains in place until your character goes to another level or you enter map view again and exit it without switching levels

**Comment by wheals** [comment] 2020-12-29 10:15
I can't reproduce this, and as such I suspect it was fixed in 726680df4ae09689c9d2fdde5337a0a63114aa5c

**Closed by wheals** 2020-12-29 10:15 UTC
Labels: ui
