### ISSUE TITLE
Game aborts when using phial of floods in Depths

### ISSUE THREAD

**Issue by Very-Blue-Berry** [crawl/crawl#3289] opened 2023-09-09 09:58 UTC
**PLATFORM and OS or BROWSER:**

Windows 10, local tiles.

**DCSS VERSION AND GAME INFORMATION:**

30.0 Game seed: 3303

**DESCRIPTION:**

Used phial of floods at a grouping of monsters in Depths. Game aborts without any error message. I can load the game again and resume where I left off. However, using phial of floods again, also produces the sudden and abrupt closing of the game.

**EXTRA FILES:**

[saves.zip](https://github.com/crawl/crawl/files/12565479/saves.zip)

**Comment by DracoOmega** [comment] 2024-11-24 04:44
I think this was fixed by 38777b0aa055626789af6181ad675a162da88d68
(At any rate, I cannot reproduce it from the save file in a current version.)

**Closed by DracoOmega** 2024-11-24 04:44 UTC
