### ISSUE TITLE
Crash when attempting to travel up a floor in wizard mode

### ISSUE THREAD

**Issue by runrin** [crawl/crawl#1244] opened 2019-12-28 23:05 UTC
offline console version 0.23.0 installed on debian 10 via apt.

attempting to travel up a floor from zot 5 using `&u` in wizard mode. reproducible using the save file provided. 

[crash-Haorphav-20191227-225641.txt](https://github.com/crawl/crawl/files/4007547/crash-Haorphav-20191227-225641.txt)
[save.zip](https://github.com/crawl/crawl/files/4007548/save.zip)

**Comment by rawlins** [comment] 2020-05-02 17:41
Sorry for the extremely slow reply on this, but this looks like a crash that happened on upgrading a save to 0.23.0 from earlier versions. This issue was fixed in 0.23.1 (and later versions such as 0.23.2, 0.24, etc), as of commit 1d7d80c6f08. I've confirmed that this crash does replicate in 0.23.0 and doesn't after 0.23.1.

**Closed by rawlins** 2020-05-02 17:41 UTC
