### ISSUE TITLE
Djinni spell tiles always grayed/greyed

### ISSUE THREAD

**Issue by mikeayer** [crawl/crawl#2216] opened 2021-11-05 20:14 UTC
**PLATFORM and OS or BROWSER:**
local tiles, macOS Monterey 12.0.1

**DCSS VERSION AND GAME INFORMATION:**
0.27.1

**DESCRIPTION:**
On the spell tiles, the Djinni always show all spells as grayed out.  However, if you're able to cast the spell, clicking works, and the spells show up correctly as available (or not) on the casting list.

**EXTRA FILES:**

![djinni_tiles](https://user-images.githubusercontent.com/93792472/140572820-bdce6320-05b5-4e8d-a043-5c1a3ea9a21f.png)
![djinni_list](https://user-images.githubusercontent.com/93792472/140572852-b13168ad-0b22-4747-830c-45409d8bed3d.png)

**Comment by mikeayer** [comment] 2021-11-05 20:28
I suspect the tiles are checking if the player has sufficient MP to cast and styling appropriately, and because the Djinni has zero it makes them look disabled.

**Comment by robertxgray** [comment] 2021-11-12 13:07
Duplicate of #2091. It should be fixed on trunk.

**Comment by rawlins** [comment] 2021-11-21 13:23
Yes, this should be fixed; it'll also be backported to 0.27.2.

**Closed by rawlins** 2021-11-21 13:23 UTC
