### ISSUE TITLE
Teleporting in cheibrodos_lair_end_hotspot

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#2733] opened 2022-09-17 21:56 UTC
**PLATFORM and OS or BROWSER:**
Linux 3.16.0 console using XTerm(358)

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-125-g51eefa89be

**DESCRIPTION:**
"A sudden malevolance" teleported my character into the room in cheibrodos_lair_end_hotspot with the dragon and the runed door.

I expected to have to open the door or breach the wall before I could enter.

**Comment by kd7uiy** [comment] 2022-10-03 22:15
Per the documents found at https://github.com/crawl/crawl/blob/master/crawl-ref/docs/develop/levels/guidelines.md#guidelines-for-no_tele_into , "Any old runed door / transporter vault. It's fine for players to teleport into tough or scary situations."

Suggest closing this as not a bug.

**Comment by Aliscans** [comment] 2022-10-04 22:15
It's a judgement call. You probably don't have fire resistance by that point, so it's up to 72 points of damage in one breath attack, and the door means you have no way to remove yourself immediately from the situation. Is that egregious?

**Comment by Picklenugget1** [comment] 2022-10-07 17:41
Actually, the door helps a lot, as closing it in the dragon's face will get rid of it until you decide to fight it. Also, the breath counter allows plenty of time for an efficient player to rectify the situation before taking more damage.

**Comment by regret-index** [comment] 2024-09-20 09:44
Three vaults placed before the end of Lair (`bobbens_dragon_lair_wall`, `hibernation_bobbens`, and `dragon1_lemuel`) as well as two other Lair ends with dragons (`wormcave`, `guppyfry_lair_end_dragon`) all allow teleporting blindly into fire dragons. Runed doors do not always need no_tele_into flagging, and if not for the fact the vault's molten gargoyles would have the fire dragon join the other volcano monsters behind a regular door, I'd just have removed the runed door from a Lair end already.

The only reason to keep this report open is as a reminder to figure out a way to reconfigure the vault to not use a runed door, which can be left in the vault header comments themselves.

**Closed by regret-index** 2024-09-20 09:44 UTC
Labels: vaults, gameplay
