### ISSUE TITLE
Oddities with options - autopickup } doesn't work as expected- "tins of tremorstones" not counted as misc (in Stable and Trunk) (on CKO)

### ISSUE THREAD

**Issue by culcube** [crawl/crawl#2851] opened 2022-11-28 12:22 UTC
**PLATFORM and OS or BROWSER:**
console - crawl.kelbi.org

**DCSS VERSION AND GAME INFORMATION:**
0.29.1-2-gbd0b4ee654 (stable)
0.30-a0-377-g5cb311bc9f (trunk)

**DESCRIPTION:**
(this is one of two reports that might be connected)
In my options I have the following autopickup exception:
autopickup_exceptions += <} 

When I start a game the misc. items are almost all selected, with only "tins of tremorstones" still excluded.

**EXTRA FILES:**
(none needed)

**Comment by DevJac** [comment] 2023-08-12 03:57
Duplicate of https://github.com/crawl/crawl/issues/2671

**Comment by wheals** [comment] 2024-01-13 17:37
Closing as duplicate.

**Closed by wheals** 2024-01-13 17:37 UTC
Labels: configuration
