### ISSUE TITLE
Trojan detected in the Windows installer

### ISSUE THREAD

**Issue by jcbollinger** [crawl/crawl#3132] opened 2023-05-14 15:58 UTC
**PLATFORM and OS or BROWSER:**
Windows 10; local

**DCSS VERSION AND GAME INFORMATION:**
0.30.0

**DESCRIPTION:**
BitDefender antivirus claims to detect a trojan in the Windows installer download (https://github.com/crawl/crawl/releases/download/0.30.0/dcss-0.30.0-win32-installer.exe).  Specifically, it says:

> The file C:\...\dcss-0.Ih3PagLr.30.0-win32-installer(1).exe.part is infected with Gen:Trojan.Heur.FU.@JZ@aGLZuBhi. The threat has been successfully blocked, your device is safe.

**EXTRA FILES:**
(none)

**Comment by Zireael07** [comment] 2023-05-14 16:44
Heur likely stands for "Heuristics" - which in plain text means it's bull**** (many av software love to claim this when the file in question is very new and hasn't seen many downloads yet)

**Comment by robertxgray** [comment] 2023-05-14 20:18
I have reported the false positive to BitDefender. It worked when the Android port had a similar problem with Avast. I hope this will be solved in a few days.

https://www.bitdefender.com/consumer/support/answer/29358/?success=1

**Comment by robertxgray** [comment] 2023-05-14 20:35
That was fast:

> Thank you for your file submission.
> 
> The file has been automatically sent to our laboratories for specialized analysis. If the file is indeed a False Positive,
> the detection will be removed in the next 72 hours and the modification will be implemented in the product through 
> a Signature Update. Please keep your Bitdefender up-to-date.
> 
> Please be informed that this is an automated process. Reply to this email if you have any other issues regarding 
> your Bitdefender product and one of our engineers will take over.
>
>Have a nice day!

**Comment by robertxgray** [comment] 2023-05-14 20:42
Dammit, I missed the "IF". 🤦🏾‍♀️

**Comment by robertxgray** [comment] 2023-05-20 09:45
I didn't get any more messages from BitDefender. Please @jcbollinger, can you confirm if the problem is solved? I hope it is because I'm not sure which is the next step otherwise.

**Comment by jcbollinger** [comment] 2023-05-20 17:02
I downloaded the installer again (same file, I think) and used it to install Crawl.  BitDefender did not complain about it this time, so I think the problem is resolved.

**Comment by rawlins** [comment] 2023-05-20 20:56
Thanks for the update! I'm going to close this up.

I wonder if we should simply consider dropping the installer distribution, it's a perpetual source of false positives.

**Closed by rawlins** 2023-05-20 20:56 UTC
