### ISSUE TITLE
Ball lightning explodes early

### ISSUE THREAD

**Issue by Monkooky** [crawl/crawl#2775] opened 2022-10-10 02:25 UTC
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**

**DESCRIPTION:**
When ball lightning moves up to an enemy then explodes, the explosion is centered two spaces away from the monster rather than adjacent to the monster. Seems to occur on almost every ball lightning trigger; should be easy to reproduce.

**EXTRA FILES:**
![image](https://user-images.githubusercontent.com/6244827/194791017-092bc60f-008b-4e05-8dc2-0b4bd1ebc0f4.png)

![image](https://user-images.githubusercontent.com/6244827/194791058-d3b7a66a-d37f-4687-8765-e1664d40f074.png)

**Comment by Picklenugget1** [comment] 2022-10-11 11:26
Actually, the rest is off-screen, it's a 7 by 7 explosion

**Comment by Monkooky** [comment] 2022-10-13 00:06
![194791058-d3b7a66a-d37f-4687-8765-e1664d40f074](https://user-images.githubusercontent.com/6244827/195469684-49ef4f61-2b67-4385-9b72-de4065ba543a.png)

**Comment by Picklenugget1** [comment] 2022-10-13 11:46
Huh, guess i'm wrong, sorry

**Comment by kd7uiy** [comment] 2022-11-02 18:51
So serious question, is this actually a bug, or is it designed as intended? I can't find anywhere where it says that the balls are supposed to explode right next to monsters...

**Comment by PleasingFungus** [comment] 2024-01-07 23:06
Ball lightnings try to explode whenever they're within two grid spaces of the target - that is, adjacent or one space away from adjacent. This has been the case essentially forever - it traces back to somewhere before Stone Soup.

I have no strong opinion on changing this, so I'm closing the issue, but let me know if you think it *should* work differently.

**Closed by PleasingFungus** 2024-01-07 23:06 UTC
Labels: gameplay
