### ISSUE TITLE
Map named 'hangedman_elemental_grid_stream' already loaded

### ISSUE THREAD

**Issue by arteymix** [crawl/crawl#2414] opened 2022-02-11 18:11 UTC
I think my 0.27.1 save is causing an issue with the newly released 0.28.0. This issue does not occur with a clean `~/.crawl`.

```
/app/share/crawl/dat/des/branches/hells.des:75: Map named 'hangedman_elemental_grid_stream' already loaded at /app/share/crawl/dat/des/branches/geh.des:139
```

I'm building crawl 0.28.0 on freedesktop 21.08 Flatpak platform for the "official" Flathub package https://github.com/flathub/org.develz.Crawl. I'm using the tile mode.

Here's my [.crawl.tar.gz](https://github.com/crawl/crawl/files/8050802/default.crawl.tar.gz) if you need to reproduce it.

**Comment by robertxgray** [comment] 2023-05-13 15:50
I was able to reproduce the problem with newer Flatpak builds. It seems the bug is Flatpak specific, if you run another build of the game first then you can safely run the Flatpak one.

**Comment by robertxgray** [comment] 2023-05-13 16:59
It looks like the code to detect outdated caches is not working. More info here: https://github.com/crawl/crawl/issues/1702

There may be a Flatpak solution for this, but I'm afraid I lack the knowledge to provide it. Otherwise, the workaround provided by Crawl would be easy to implement: https://github.com/robertxgray/org.develz.Crawl/commit/df55628b61cde7bc6e02a2c0913826178da0feac

Just made a quick test and it seems to work okay. Do you want me send a PR to Flathub?

**Comment by arteymix** [comment] 2023-05-13 18:33
Sure!

It might have something to do with how the filesystem timestamp operate in a container. I'll see if there's a way to adjust this.

**Comment by arteymix** [comment] 2023-05-13 18:35
It appears that ostree resets the timestamps to zero when packaging, so we might not have a choice but to have versioned files.

https://github.com/flatpak/flatpak/issues/3064

**Comment by arteymix** [comment] 2023-05-13 18:37
Since there's no workaround, I'll take your patch.

An alternative would be to not retain the cache directory on restart at the cost of a possibly slower startup time.

**Comment by robertxgray** [comment] 2023-05-14 09:53
I see the PR has been merged in Flathub, so I'm closing the issue. Thank you.

**Closed by robertxgray** 2023-05-14 09:53 UTC
Labels: linux, crash
