### ISSUE TITLE
Crashed on waiting w/ barb status.

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#2524] opened 2022-04-10 19:28 UTC
**PLATFORM and OS or BROWSER:**
0.29-a0-323-g050149af67 webtiles trunk

**DESCRIPTION:**
https://cbro.berotato.org/morgue/ardl/crash-ardl-20220410-190453.txt
Finished a fight in which i was barb'd by a red devil. Then I pressed 5 to wait it out. then the game crashed. I was sent beack to the last time i entered the floor when i re-opened the game so idk how useful this save will be.

 https://cbro.berotato.org/saves/ardl-crawl-git-050149af67-220410-1927.tar.bz2

**Comment by semitonal** [comment] 2022-04-23 20:27
Closing as a duplicate of #2405 - I haven't been able to reproduce it but it does seem like both cases are crashes somehow caused by resting off barbs triggering the failsafe against endless runrest delays.

**Closed by semitonal** 2022-04-23 20:27 UTC
