### ISSUE TITLE
Crashing on loading a save, trunk version

### ISSUE THREAD

**Issue by Visscera** [crawl/crawl#1346] opened 2020-04-12 03:12 UTC
**PLATFORM and OS or BROWSER:**
Windows, local tiles, trunk

**DCSS VERSION:**
The save was made in 0.25-a0-549-g6e6e6501ad, with no issues with loading any other saves before.
The crash still happens when trying to load the save in the latest trunk, 0.25-a0-737-g26c3a87c45.

**DESCRIPTION:**
When trying to load my latest save of my latest character, the game simply crashes to the desktop. It's a GnFi'Zin, standing right before the Orb of Zot. I've had no troubles loading the save with this character (or any other one, for that matter) before, the game didn't crash mid-save or anything like that and my hard drive is only a few months old - I haven't noticed any accidental file corruptions before - so I assumed it is probable that this might be some obscure bug in the saving subroutines.
The game crashes consistently each time I'm trying to load the save.

**EXTRA FILES:**
The save file in question!
[Krexre_crashing_save.zip](https://github.com/crawl/crawl/files/4465792/Krexre_crashing_save.zip)

**NOTES**
I don't really expect the save file to be repaired or anything, though, of course, it's very sad to lose my first legit almost complete 14-rune run. Aw. But I hope it will help with bug fixing, at least. :3

**Comment by aidanholm** [comment] 2020-04-12 08:23
Thanks for reporting; it's not a corrupted save, it's a bug in the game where some gnoll-specific messaging (related to their skills) happens before the message display is set up, causing a crash. So you will be able to continue playing your character once it is fixed.

**Comment by Goratrix** [comment] 2020-04-12 09:53
Hi Aidan, not sure if you saw the follow up in this ticket: https://crawl.develz.org/mantis/view.php?id=12174&nbn=3#bugnotes, that one is just a cosmetic issue now, so doesn't matter much, I just thought I mention it here, because it's the same root cause (order of execution of messages and the message window).

**Comment by aidanholm** [comment] 2020-04-12 11:26
That's actually slightly different, because it's caused by (IIRC) the `more()` code doing a redraw before the dungeon view has filled out a buffer of what to draw. This crash is `mprf()` printing to a nonexistent buffer that is (not yet) created by the render code. The underlying issue is indeed the same though: various bits of crawl all do their own drawing to the screen (e.g. `more()` directly redrawing, instead of enqueuing a redraw). Work on fixing this (by moving to unified render code) is on the way, but won't be ready any time soon.

**Closed by aidanholm** 2020-04-12 11:26 UTC

**Comment by aidanholm** [comment] 2020-04-12 11:30
@Visscera crash fixed at 0.25-a0-742-gbe65d2b; time to go get that golden rune!

**Comment by Visscera** [comment] 2020-04-27 15:53
> @Visscera crash fixed at 0.25-a0-742-gbe65d2b; time to go get that golden rune!

@aidanholm, yaaay! Thank you!!!
