### ISSUE TITLE
Octopodes casting Beastly Appendage Get Worn Hats Melded, Even Though They Don't Get The Horns Mutation (Or Any Other Head Mutations) When Casting It Due To Racial Restrictions

### ISSUE THREAD

**Issue by Lanelorn** [crawl/crawl#2919] opened 2023-01-08 04:22 UTC
**PLATFORM and OS or BROWSER:**
<Local tiles, Window 10>

**DCSS VERSION AND GAME INFORMATION:**
<0.29.1>

**DESCRIPTION:**
<Casting Beastly Appendage as an Octopode causes worn hats to meld, despite Octopodes only receiving Tentacle Spike 3 from the spell (they get no horns auxiliary attack mutation but Tentacle Spike at 3 as compensation.  This makes no sense, the whole reason headgear melds is to accommodate horns which aren't granted for Octopodes.>

**Comment by acrobat3** [comment] 2023-01-08 19:54
https://github.com/crawl/crawl/issues/1699
> This is intended behaviour, as per https://github.com/crawl/crawl/commit/0fb1eaa16f565cf8f24ce8fde4a9668d196e706b (so that Op don't just get to cast Appendage with no downside at all).

**Comment by Lanelorn** [comment] 2023-01-08 23:56
That seems both realistically dumb and unnecessarily punishing - Octopodes already are stuck with an AC of 1 that's nearly unalterable in the early game barring finding an AC ring, a rand-art weapon or shield, or an amulet.  That's it until they can cast something like ice form.  Other races that cast Appendages lose 2 not terrible important slots out of all the possible option types, Octopodes lose 1/3 of their total potential option types.  This is unnecessarily punishing in spades - Octopodes are already plenty screwed early game - they don't need this.  Especially when it's directly illogical

**Comment by Lanelorn** [comment] 2023-01-09 00:13
Ok technically 1/5 counting possible randart weapons and shields, but still it's nuts.  Note also they're already being disadvantaged by this spell.  One level 3 tentacle spike added by the spell - One 8 damage attack added.  Level 2 horns and talons being added?  One 11 damage plus one 10 damage attack added.  And they need to lose a slot on top of that for no discernable reason?  You'd have to do a lot more than not make hats meld to even make it equal to what other races get out of it - by far

**Comment by semitonal** [comment] 2023-01-20 21:11
Closing - as noted, this is intended behaviour. The spell's description didn't clearly explain what was happening, so this has now been updated.

**Closed** 2023-01-20 21:11 UTC
